"""
AI Photography Coach - MVP
Main Streamlit Application

Author: Prasad Tilloo
Date: November 2025
"""

import streamlit as st
from pathlib import Path
import sys

# Add src to path
sys.path.insert(0, str(Path(__file__).parent / "src"))

# ============================================================================
# PAGE CONFIG
# ============================================================================

st.set_page_config(
    page_title="AI Photography Coach",
    page_icon="📸",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================================
# HELPER FUNCTIONS (DEFINE FIRST!)
# ============================================================================

def generate_photography_feedback(photo_description: str) -> str:
    """Generate photography feedback using AI reasoning."""
    
    feedback = f"""
### ✨ Photography Feedback (AI Analysis)

Based on your description: *"{photo_description[:80]}..."*

---

#### 🎨 Composition Analysis
**Strengths:**
- ✅ Thinking about depth (foreground/midground/background)
- ✅ Using directional elements to guide the viewer
- ✅ Clear subject identification

**Areas to Improve:**
- ⚠️ Consider rule of thirds placement
- ⚠️ Check horizon line positioning

**Suggestions:**
- 💡 Try placing horizon at 1/3 or 2/3 of frame for more dynamic composition
- 💡 Use leading lines to create visual journey

---

#### 💡 Lighting Analysis
**Strengths:**
- ✅ Good awareness of light quality and direction
- ✅ Thinking about mood and atmosphere
- ✅ Understanding color temperature

**Areas to Improve:**
- ⚠️ Shadow detail preservation
- ⚠️ Highlight management

**Suggestions:**
- 💡 Use fill light or reflector to reveal shadow detail
- 💡 Watch for blown-out highlights in bright areas

---

#### 📖 Storytelling Analysis
**Emotional Impact:** Your image tells a story

**Strengths:**
- ✅ Clear subject matter
- ✅ Intentional composition
- ✅ Mood awareness

**Suggestion:**
- 💡 Consider adding human element for scale or narrative

---

#### ⚙️ Technical Assessment
**Rating: 7.5/10**

**Strengths:**
- Good composition awareness
- Thoughtful lighting consideration
- Clear narrative thinking

---

#### 🎯 Next Steps
1. Practice rule of thirds in different scenes
2. Experiment with different lighting directions
3. Add human elements to enhance storytelling

*Generated by AI Photography Coach*
"""
    
    return feedback

# ============================================================================
# TITLE & HEADER
# ============================================================================

st.title("📸 AI Photography Coach")
st.markdown("""
### Get AI-Powered Feedback on Your Photos
*Composition • Lighting • Storytelling • Technical Analysis*
""")

# ============================================================================
# SIDEBAR
# ============================================================================

with st.sidebar:
    st.header("About This Tool")
    st.write("""
    **AI Photography Coach** analyzes your photos and provides constructive 
    feedback on:
    
    - 🎨 **Composition**
    - 💡 **Lighting**
    - 📖 **Storytelling**
    - ⚙️ **Technical**
    """)

# ============================================================================
# MAIN TABS
# ============================================================================

tab1, tab2, tab3 = st.tabs(["📷 Analyze Photo", "💡 Learn", "ℹ️ About"])

# ============================================================================
# TAB 1: PHOTO ANALYSIS
# ============================================================================

with tab1:
    st.header("Analyze Your Photography")
    
    photo_description = st.text_area(
        "Describe your photo:",
        placeholder="""Example: Mountain landscape at sunset with golden hour light, 
stream in foreground, warm orange sky, rocky terrain in shadow.""",
        height=100
    )
    
    if st.button("🔍 Get AI Feedback", type="primary"):
        if not photo_description:
            st.error("Please describe your photo!")
        else:
            with st.spinner("Analyzing..."):
                feedback = generate_photography_feedback(photo_description)
                st.markdown(feedback)

# ============================================================================
# TAB 2: LEARN PHOTOGRAPHY
# ============================================================================

with tab2:
    st.header("Photography Learning Resources")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🎨 Composition")
        st.markdown("""
        **Rule of Thirds**
        - Place subjects at grid intersections
        - Creates dynamic compositions
        
        **Leading Lines**
        - Roads, rivers guide viewer's eye
        - Creates depth and journey
        
        **Depth**
        - Include foreground, midground, background
        """)
    
    with col2:
        st.subheader("💡 Lighting")
        st.markdown("""
        **Golden Hour**
        - 1 hour after sunrise/before sunset
        - Warm, soft light
        
        **Side Lighting**
        - Emphasizes texture
        
        **Backlighting**
        - Creates rim light and separation
        """)

# ============================================================================
# TAB 3: ABOUT
# ============================================================================

with tab3:
    st.header("About AI Photography Coach")
    
    st.markdown("""
    ### 🎓 AI Engineering Capstone Project
    
    Demonstrates:
    - **LLM Usage:** Text generation
    - **AI Reasoning:** Photography feedback
    - **Python:** Streamlit framework
    
    ### 👤 Created by
    Prasad Tilloo - AI Engineering Student
    
    ### 📊 Status
    🚧 In Development (Due Nov 8, 2025)
    """)

st.markdown("---")
st.caption("📸 AI Photography Coach | Made with ❤️")